name: CI

on: [push]

#--- SECURITY SCANS ---

#sast_scan with Bandit
jobs: 
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    #check code
    - name: Checkout code
      uses: actions/checkout@v2

    #install python
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    #install bandit
    - name: Install Bandit
      run: pip install bandit

    #run bandit and output a json report file
    - name: Run Bandit scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json
    
    #upload artifact
    - name: upload Artifact
      uses: actions/upload-artifact@v4
      if: always() #always exec this step
      with:
        name: bandit-findings
        path: bandit-report.json
  
  #--- DOCKER SCANS ---
  docker_image_scan:
    name: Build docker image and run scan
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout Code
      uses: actions/checkout@v2

    #install docker
    - name: Set up docker
      uses: docker/setup-docker-action@v4
      #with: 
        #docker_version: '20.10.7'

    #exec docker commands
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        context: .
        file: ./Dockerfile

    #scan the docker image
    #- name: Docker Scout Scan
      #run: |
        #curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install.scout.sh
        #sh install.scout.sh

        #echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        
        #docker scout quickview
        #docker scout cves

    - name: Docker Scout Scan
      uses: docker/scout-action@v1.18.2
      with:
        dockerhub-user: ${{ secrets.DOCKER_USER }}
        dockerhub-password: ${{ secrets.DOCKER_PASS }}
        command: quickview, cves
        only-severities: critical, high
        sarif-file: scout-report.sarif

     #upload artifact
    - name: upload Artifact
      uses: actions/upload-artifact@v4
      if: always() #always exec this step
      with:
        name: docker-scout-report
        path: scout-report.sarif    
