name: CI

on: [push]

#--- SECURITY SCANS ---

#sast_scan with Bandit
jobs: 
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    #check code
    - name: Checkout code
      uses: actions/checkout@v2

    #install python
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    #install bandit
    - name: Install Bandit
      run: pip install bandit

    #run bandit and output a json report file
    - name: Run Bandit scan
      run: bandit -ll -ii -r . -f json -o badit-report.json
    
    #upload artifact
    - name: upload Artifact
      uses: actions/upload-artifact@v4
      if: always() #always exec this step
      with:
        name: bandit-findings
        path: bandit-report.json
    
